In [1]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.1f' % x)

In [23]:
df = pd.read_csv('../../data/rajbrain/sud/bestsellers-may23.csv')
df['Style No'] = df.option.str.split('-').apply(lambda x: '-'.join(x[:-1]))
df['Prominent Colour'] = df.option.str.split('-').apply(lambda x: x[-1])

ean_prod_map = pd.read_csv('../../data/rajbrain/sud/ean-product-map.csv')
ean_prod_map['option'] = ean_prod_map['Style No'] + '-' + ean_prod_map['Prominent Colour']

temp1 = df[['Style No', 'Prominent Colour']].sort_values(by=['Style No', 'Prominent Colour']).drop_duplicates()
temp2 = ean_prod_map[['Style No', 'Prominent Colour']].where(ean_prod_map['Style No']._in(temp1['Style No'].unique())).sort_values(by=['Style No', 'Prominent Colour']).drop_duplicates()
# temp2 = ean_prod_map[['Style No', 'Prominent Colour']]
# temp1.merge(temp2, on=['Style No'], how='left')
temp2

# len(ean_prod_map['Style No'].unique())

# set(df.option.unique()) - set(ean_prod_map.option.unique())

# df = df.merge(ean_prod_map, on='option', how='left')
# df.set_index('EAN', inplace=True)
# df

              Style No Prominent Colour
11591  0119-CK11L42-01            White
11597  0119-CK11L42-02            Khaki
11603  0119-CK11L42-03              Red
11609  0119-CK11L42-04           Yellow
11615  0119-CK11L42-05            Black
...                ...              ...
4112         WCT-06-11            Green
4118         WCT-06-11              Red
4706            WCT-07            Black
4709            WCT-07             Blue
1018               Y-2            Black

[10848 rows x 2 columns]

In [ ]:
df styles - 1833
map styles - 9672